name: driver
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.11+13

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  adaptive_theme: ^3.6.0
  app_to_foreground: ^0.0.3
  args: ^2.5.0
  assets_audio_player: ^3.1.1
  awesome_drawer_bar: ^1.2.0
  awesome_notifications_core: ^0.9.3
  awesome_notifications: ^0.9.3+1
  basic_utils: ^5.7.0
  cached_network_image: ^3.3.1
  circular_countdown_timer: ^0.2.3
  cloud_firestore: 5.0.2
  colornames: ^0.1.0
  contained_tab_bar_view: ^0.8.0
  cool_alert: ^2.0.1
  country_picker: 2.0.26
  cupertino_icons: ^1.0.6
  currency_formatter: ^2.2.1
  custom_faqs:
    git:
      url: https://github.com/ambrosethebuild/custom_faqs
      ref: main
  custom_sliding_segmented_control: ^1.8.3
  dartx: ^1.2.0
  dio: ^5.4.3+1
  dotted_line: ^3.2.2
  double_back_to_close: ^2.0.0
  file_picker: ^8.0.5
  file_sizes: ^1.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  firestore_chat: ^0.1.2
  dash_chat_2: ^0.0.21
  fl_location: ^3.1.0
  location: ^7.0.0
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_fgbg: ^0.3.0
  flutter_form_builder: ^9.3.0
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3
  flutter_image_compress: ^2.3.0
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_overboard: ^3.1.3
  flutter_overlay_window: ^0.4.4
  flutter_polyline_points: ^2.0.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.6
  #geoflutterfire2: ^2.3.15
  #geoflutterfire_plus: ^0.0.21
  geolocator: ^12.0.0
  georange: ^1.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  hand_signature: ^3.0.3
  in_app_review: ^2.0.9
  inspection: ^0.0.13
  intl: ^0.19.0
  jiffy: ^6.3.1
  localize_and_translate: ^5.1.2
  map_launcher: ^3.3.1
  measure_size: ^4.0.0
  package_info: ^2.0.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  pull_to_refresh_flutter3: ^2.0.2
  qr_code_scanner: ^1.0.1
  random_string: ^2.3.1
  rolling_switch: ^0.0.2
  schedulers: ^1.0.1
  shared_preferences: ^2.2.3
  singleton: ^0.0.3-nullsafety
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.1.0
  stacked: 3.4.3
  supercharged: ^2.1.1
  swipebuttonflutter: ^1.0.0
  timelines: ^0.1.0
  upgrader: ^10.3.0
  url_launcher: ^6.3.0
  velocity_x: ^4.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2

dependency_overrides:
  intl: ^0.18.1
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  translator: ^1.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/mealknight.jpg"
  adaptive_icon_foreground: "assets/images/mealknight.jpg"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/mealknight.jpg"
    background_color: "#ffffff"
    theme_color: "#0000FF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/json/
    - assets/lang/